server:
  port: 8080

spring:
  application:
    name: bookingtour
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingtour
    username: postgres
    password: password # Replace with your actual pg password if different
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always # Always run schema.sql to ensure table exists

mybatis:
  type-aliases-package: com.danh.bookingtour.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # 256-bit secret key
  expiration: 86400000 # 1 day in ms
